### ISSUE TITLE
Definition of object

### ISSUE THREAD

**Issue by Flogex** [vasilakisfil/Introspected-REST#13]
> `Users` and `User` are 2 distinct resources which are often, mistankenly, misthought as a single, one, resource. Also, the fact that `Users` is a collection of `User` objects is because it suits our needs but it doesn’t have necessarily to be like that.

In my understanding, `Users` is one resource which serves as a collection of **many** `User` resources. 

How do you define an _object_? Do you see a resource as the "class" and objects as the "instances" of it?

**Comment by vasilakisfil** [comment]
Yeah I would say an object is an instantiated resource, although there aren't concrete definitions for these things. Closing, feel free to re-open.
